### ISSUE TITLE
The regionSpan can change slightly

### ISSUE THREAD

**Issue by plu** [choefele/CCHMapClusterController#20]
Hi Claus,

I've noticed the clusters to rearrange when I programmtically change the region of the map. When the user is moving the map by hand, everything is fine and the clusters stay the same. But whenever I use `setCenterCoordinate:animated:` or `setRegion:animated:`, the annotation clusters rearrange themselves. I've noticed that the `CCHMapClusterController` stores the `MKCoordinateSpan` right before the region is changed, and compares it to the new span afterwards.
In the documentation of `setCenterCoordinate:animated:` Apple promises:

```
Changing the center coordinate centers the map on the
new coordinate without changing the current zoom level.
```

This is true from a human point of view. At least I cannot see the map zoom in. But the span value changes slightly. I've created a branch here to illustrate the issue: https://github.com/plu/CCHMapClusterController/compare/regionSpanBeforeChange

There are three commits. If you reset to the first one (5451b4f765521d5d3fb99493b1a0420ac575b712) and tap on any of the annotations, you'll see that while it's being centered, the clusters are rearranged. The other two commits are not meant to be a proper fix. Just to illustrate the difference.

Do you have any idea how to properly fix this?

Best regards,
plu

**Comment by mikrobi** [comment]
I'm still facing issues even with using `setVisibleMapRect:animated:`. In my app I want to center the map whenever the user selects an annotation. In general this works fine, but in case of a big zoom level, the map view somehow ignores the `CGRect` that I pass to `setVisibleMapRect:animated:`. After setting the rect, I end up with a bigger rect than I originally passed in. I couldn't find any solutions so far. Have you experienced a similar behaviour?

**Comment by mikrobi** [comment]
I've done some testing with `mapRectThatFits:(MKMapRect)mapRect` before setting the rect via `setVisibleMapRect:(MKMapRect)mapRect animated:(BOOL)animate` like described in the docs. 

According to [the Apple Docs] (https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKMapView_Class/#//apple_ref/occ/instm/MKMapView/mapRectThatFits:), I assume that the return value of `mapRectThatFits:(MKMapRect)mapRect` should match the rect that will be applied internally when using `setVisibleMapRect:(MKMapRect)mapRect animated:(BOOL)animate`

The funny (or annoying) thing is that the calculated rect via

    MKMapRect rect = [self.mapView visibleMapRect];
    rect.origin.x = point.x - rect.size.width * 0.5;
    rect.origin.y = point.y - rect.size.height * 0.5;

never matches the rect returned by `[mapView mapRectThatFits:rect]`. The size always differs slightly by random values below 0.5. Probably caused by because of all the internal calculations, rounding and conversions by MapKit?

I haven't found any cool way to set the center coordinate or change the visible map rect by not (slightly) changing `mapView.region.span.longitudeDelta` which is used in `CCHMapClusterController` to determine if the zoom level changed after changing the map view's region.

I was thinking about adding something like a "zoom change tolerance" so that we ignore marginal zoom changes and only re-cluster when the zoom changed significantly. @choefele what do you think? Should we re-open this issue?

**Comment by mikrobi** [comment]
Hmm, the "zoom change tolerance" prevents the `CCHMapClusterController` from undesired deselections. But then it might happen, that a selected annotation disappears because it gets merged into a cluster. This is caused because a marginal change of `longitudeDelta` might trigger a "heavy" cluster re-odering like described in https://github.com/choefele/CCHMapClusterController/issues/82. Seems like these issues are highly coupled.
