### ISSUE TITLE
Using CCHMapClusterController with custom annotationView for unique location

### ISSUE THREAD

**Issue by SebC99** [choefele/CCHMapClusterController#70]
Hello,

I already have a custom annotationView subclass to display my marker on the map. And I would like to user CCHMapClusterController to show a different custom annotationView when it's a cluster (with a countLabel as in the ios example).
I thought I could test the annotation class on viewForAnnotation delegate method, to show either my custom ClusterAnnotationView if it's a CCHMapClusterAnnotation and my own custom AnnotationView otherwise, but all annotations are CCHMapClusterAnnotation now!

Then I tried to test with the isUniqueLocation property to get the unique annotation contained in the clusterAnnotation and return my custom AnnotationView in that case, but it doesn't work well...

Do you have an idea?
Thanks

**Comment by choefele** [comment]
Hi,

You have to use one custom annotation view that supports both being displayed as a cluster and being displayed as an individual marker. That's because clusters will change their contents on the fly.

Inside this custom annotation view, you can distinguish the two cases. See [this code](https://github.com/optionu/stolpersteine-ios/blob/master/Stolpersteine/iPhone/MapClusterAnnotationView.m) for an example (it shows a square for clusters with one annotation and different sized circles otherwise).

-Claus

**Comment by SebC99** [comment]
I tried too... but it doesn't seem to work very well as my 2 annotationViews have 2 different frame sizes...
But i haven't seen this code, and I'm going to try it (as I see he uses 2 sizes as well)

**Comment by choefele** [comment]
Have you found a solution to your problem?

Thanks,
Claus

**Comment by SebC99** [comment]
Unfortunately no... It doesn't seem to work well with 2 different frame sizes.. I'm still working on it!

**Comment by choefele** [comment]
Perhaps it's possible to create an annotation view with the large frame size and use a transparent background for the smaller one?

**Comment by choefele** [comment]
Is there anything I can help with at this point? Thanks

**Comment by choefele** [comment]
I haven't heard back in a while so I'm closing this issue for now. Feel free to reopen when you have more information.

Thanks

**Comment by SebC99** [comment]
Sorry I had no time to try again, but the same frame size is not a solution, because of the touch areas.
