### ISSUE TITLE
Clusterin level issue

### ISSUE THREAD

**Issue by erdemgc** [choefele/CCHMapClusterController#74]
Hi,

I have integrated to your awesome library to my project, but  there is problem when my zoom level is high. When i go in deep on map, my annotations does not divide. For instance; it stays at 25, but these places are not very close to each other. Is there a parameter to set it? It seems your example project does it but mine not.

**Comment by choefele** [comment]
Perhaps you forgot to implement [`mapClusterController:willReuseMapClusterAnnotation:`](https://github.com/choefele/CCHMapClusterController/blob/master/CCHMapClusterController%20Example%20iOS/CCHMapClusterController%20Example%20iOS/MapViewController.m#L163)? 

I suggest to use the example in this repo and swap the data to yours to check where the problem is located.

**Comment by erdemgc** [comment]
i have already implemented that method, everything seems identical to example repo

**Comment by choefele** [comment]
Can you try using the example code and add your data to see if the problem persists? Otherwise, I need an example project that reproduces the issue.

**Comment by choefele** [comment]
Is there anything I can help with at this point?

**Comment by erdemgc** [comment]
unfortunately, still the same. I may not be able to send you the project according to privacy. How can we advance?

**Comment by choefele** [comment]
I'll need some way to reproduce the issue, otherwise I can't help you. It should be possible to use similar data than yours in the sample app.

**Comment by erdemgc** [comment]
@choefele i solved, it was one of my method while converting locations according to locale.

Thank you

**Comment by choefele** [comment]
Glad you solved your problem
