### ISSUE TITLE
Annotations in the same location 

### ISSUE THREAD

**Issue by lexin** [choefele/CCHMapClusterController#75]
I have 3 points with same coordinate. So, they always in the cluster. 

that is my code 
self.mapClusterController = [[CCHMapClusterController alloc] initWithMapView:self.mapView];
		self.mapClusterController.delegate = self;
		self.mapClusterer = [[CCHNearCenterMapClusterer alloc] init];
		self.mapClusterController.clusterer = self.mapClusterer;

		self.mapClusterController.cellSize = 50;
		self.mapClusterController.marginFactor = 1;

		self.mapClusterController.maxZoomLevelForClustering = 12;

![2015-02-19 09 23 06](https://cloud.githubusercontent.com/assets/367295/6263034/f207d218-b818-11e4-8cfc-918207900e49.png)
![2015-02-19 09 22 54](https://cloud.githubusercontent.com/assets/367295/6263033/f20737f4-b818-11e4-9267-9ec4083b6bd6.png)

How to devide them? I have tried  maxZoomLevelForClustering and  minUniqueLocationsForClustering with different values, but It doesn't help.

**Comment by choefele** [comment]
If annotations are in the exact same location, `CCHMapClusterController` will never split them up (otherwise, the annotations would be rendered on top of each other and not be accessible). `maxZoomLevelForClustering` and `minUniqueLocationsForClustering` are for annotations at different locations.

-Claus

**Comment by lexin** [comment]
ok, Thank You.
