### ISSUE TITLE
Animate annotations

### ISSUE THREAD

**Issue by mikrobi** [choefele/CCHMapClusterController#81]
Any cool idea about how to achieve an animation like this: http://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html

**Comment by choefele** [comment]
This type of animation is not yet possible with the current interfaces. 

#10 contains a prototype of an implementation. This wasn't merged because it lacked unit tests and because I don't think associate objects are needed to implement this feature. Perhaps you can have a look and see if you can improve the implementation.

-Claus

**Comment by mikrobi** [comment]
I will have a look!

**Comment by choefele** [comment]
Closing this in favor of #10
